server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;serverTimezone=GMT%2B8&amp;characterEncoding=utf8
    username: root
    password:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update